Repository Baconeta-Studios/setting-the-stage, pull requests merged in 2024-06, with the labels that each got.

#89 Update README.md
  README.md
Labels: project management

#83 Camera control
  Assets/Art/Stage.meta
  Assets/Art/Stage/Material.001.mat
  Assets/Art/Stage/Material.001.mat.meta
  Assets/Art/Stage/StageV1.fbx
  Assets/Art/Stage/StageV1.fbx.meta
  Assets/Art/Stage/TEMP_Stage.png
  Assets/Art/Stage/TEMP_Stage.png.meta
  Assets/Art/TEMP_Person.png
  Assets/Art/TEMP_Person.png.meta
  Assets/Art/TEMP_Person2.png
  Assets/Art/TEMP_Person2.png.meta
  Assets/Art/TEMP_Person3.png
  Assets/Art/TEMP_Person3.png.meta
  Assets/Input.meta
  Assets/Input/InputSystem.inputsettings.asset
  Assets/Input/InputSystem.inputsettings.asset.meta
  Assets/Input/SettingTheStage.inputactions
  Assets/Input/SettingTheStage.inputactions.meta
  Assets/Prefabs/Backdrop.prefab
  Assets/Prefabs/Camera.prefab
  Assets/Prefabs/Camera.prefab.meta
  Assets/Prefabs/InputSystem.prefab
  Assets/Prefabs/InputSystem.prefab.meta
  Assets/Prefabs/MainCamera.prefab
  Assets/Prefabs/Musicians/Musician_Billy.prefab
  Assets/Prefabs/Musicians/Musician_Carmen.prefab
  Assets/Prefabs/Musicians/Musician_Fynch.prefab
  Assets/Prefabs/Stage.prefab
  Assets/Prefabs/Stage.prefab.meta
  Assets/Prefabs/StagePosition.prefab
  Assets/Prefabs/StageSelection.prefab
  Assets/Prefabs/UI/ChapterCanvas.prefab
  Assets/Prefabs/UI/StarContainer.prefab
  Assets/Scenes/Act 1 Chapter 1.unity
  Assets/Scenes/Act 1.unity
  Assets/Scripts/GameStructure/ActCanvas.cs
  Assets/Scripts/GameStructure/ChapterUI.cs
  Assets/Scripts/Objects/CoreObjects/Musician.cs
  Assets/Scripts/Objects/StSBillboard.cs
  Assets/Scripts/Objects/StSBillboard.cs.meta
  Assets/Scripts/Objects/StSObject.cs
  Assets/Scripts/UI/CoreGameplay/Carousel/Carousel.cs
  Assets/Scripts/UI/CoreGameplay/Stage/StagePosition.cs
  Assets/Scripts/UI/CoreGameplay/Stage/StageSelection.cs
  Assets/Scripts/Utils/StSCamera.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: programming

#101 Feature/add slice narrative layout
  Assets/Prefabs/Acts/Act 1.prefab
  Assets/Prefabs/Narrative/SliceBarNarrative.prefab
  Assets/Prefabs/Narrative/SliceBarNarrative.prefab.meta
  Assets/Scripts/GameStructure/Act.cs
  Assets/Scripts/GameStructure/NarrativeSystem.cs
  Assets/Scripts/Managers/NarrativeDataManager.cs
Labels: graphics

#106 Change spotlight selection
  Assets/Prefabs/StageSelection.prefab
  Assets/Prefabs/UI/ChapterCanvas.prefab
  Assets/Scenes/Act 1 Chapter 1.unity
  Assets/Scripts/GameStructure/ChapterUI.cs
  Assets/Scripts/UI/CoreGameplay/Stage/StagePosition.cs
  Assets/Scripts/UI/CoreGameplay/Stage/StageSelection.cs
  Assets/Scripts/Utils/StSCamera.cs
Labels: programming

#105 Made a scrolling system for the narratives
  Assets/Prefabs/Acts/Act 1.prefab
  Assets/Prefabs/Narrative/ScrollableNarrative.prefab
  Assets/Prefabs/Narrative/ScrollableNarrative.prefab.meta
  Assets/Scripts/GameStructure/Narrative/NarrativeLayout.cs
  Assets/Scripts/GameStructure/Narrative/NarrativeLayoutScrolling.cs
  Assets/Scripts/GameStructure/Narrative/NarrativeLayoutScrolling.cs.meta
Labels: programming

#109 Fix/mobile build issues
  Assets/AddressableAssetsData/AddressableAssetSettings.asset
  Assets/AddressableAssetsData/Android.meta
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  Assets/AddressableAssetsData/AssetGroups/PerformanceActAudioData.asset
  Assets/AddressableAssetsData/AssetGroups/PerformanceActAudioData.asset.meta
  Assets/AddressableAssetsData/AssetGroups/Schemas/PerformanceActAudioData_BundledAssetGroupSchema.asset
  Assets/AddressableAssetsData/AssetGroups/Schemas/PerformanceActAudioData_ContentUpdateGroupSchema.asset
  Assets/AddressableAssetsData/ProfileDataSourceSettings.asset
  Assets/AddressableAssetsData/ProfileDataSourceSettings.asset.meta
  Assets/Data/ChapterSo/ChapterAudio_ChapterOne.asset
  Assets/Prefabs/SceneLoader.prefab
  Assets/Scenes/Act 1.unity
  Assets/Scenes/Act 2.unity
  Assets/Scenes/MainMenu.unity
  Assets/Scripts/Audio/PerformanceAudioDataLoader.cs
  Assets/Scripts/Audio/PerformanceAudioDataManager.cs
  Assets/Scripts/Managers/SceneLoader.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/Packages/com.eflatun.scenereference/Settings.json
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ScriptableBuildPipeline.json
Labels: programming

#112 Feature/add settings popup
  Assets/Prefabs/UI/ChapterCanvas.prefab
  Assets/Prefabs/UI/Settings/SettingsPopup.prefab
  Assets/Prefabs/UI/Settings/SettingsPopup.prefab.meta
  Assets/Scripts/GameStructure/Chapter.cs
  Assets/Scripts/GameStructure/ChapterUI.cs
  Assets/Scripts/UI/Settings/SettingsPopup.cs
  Assets/Scripts/UI/Settings/SettingsPopup.cs.meta
Labels: programming

#117 Fix/issues/116
  Assets/Scripts/GameStructure/Act.cs
  Assets/Scripts/GameStructure/ActCanvas.cs
  Assets/Scripts/GameStructure/Chapter.cs
  Assets/Scripts/GameStructure/ChapterUI.cs
  Assets/Scripts/Managers/SceneLoader.cs
  Assets/Scripts/UI/CoreGameplay/Stage/StagePosition.cs
  Assets/Scripts/UI/CoreGameplay/Stage/StageSelection.cs
  Assets/Scripts/UI/MusicianInfoPanel.cs
  Assets/Scripts/Utils/StSCamera.cs
Labels: bug

#118 Add new stage model
  Assets/Art/Stage/Material.001.mat
  Assets/Art/Stage/Material.001.mat.meta
  Assets/Art/Stage/STAGE07_re.fbx
  Assets/Art/Stage/STAGE07_re.fbx.meta
  Assets/Art/Stage/StageV1.fbx
  Assets/Art/Stage/TEMP_Stage.png
  Assets/Art/Stage/final_barestage.png
  Assets/Art/Stage/final_barestage.png.meta
  Assets/Prefabs/Stage/Stage.prefab
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Electronic Highway Sign SDF.asset
Labels: asset implementation

#104 Lay groundwork for analytics subsystem
  Assets/Scenes/MainMenu.unity
  Assets/Scripts/Achievements/AchievementsSystem/AchievementController.cs
  Assets/Scripts/Analytics/AnalyticsHandlerBase.cs
  Assets/Scripts/Analytics/AnalyticsHandlerBase.cs.meta
  Assets/Scripts/Analytics/UnityAnalytics.cs
  Assets/Scripts/Analytics/UnityAnalyticsHandler.cs
  Assets/Scripts/Analytics/UnityAnalyticsHandler.cs.meta
  Assets/Scripts/GameStructure/Act.cs
  Assets/Scripts/UI/EditorAndBuildSwitcher.cs
  Assets/Scripts/Utils/ClassHelpers.cs
  Assets/Scripts/Utils/ClassHelpers.cs.meta
  Assets/Scripts/Utils/SaveSystem.cs
  Assets/Scripts/Utils/StSDebug.cs
  Assets/Scripts/Utils/UnityHelper.cs
  Assets/Scripts/Utils/UnityHelper.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/UnityConnectSettings.asset
Labels: programming

#144 Add analytics consent
  .gitignore
  .vsconfig
  Assets/Art/UI/toggle-button.png
  Assets/Art/UI/toggle-button.png.meta
  Assets/Fonts/Lato/Lato-Black SDF.asset
  Assets/Scenes/MainMenu.unity
  Assets/Scripts/Analytics/AnalyticsHandlerBase.cs
  Assets/Scripts/Analytics/UnityAnalyticsHandler.cs
  Assets/Scripts/UI/Settings/ToggleAnalytics.cs
  Assets/Scripts/UI/Settings/ToggleAnalytics.cs.meta
  Assets/Scripts/Utils/UnityHelper.cs
Labels: programming

#150 Fix bug #149
  Assets/Scripts/UI/Settings/ToggleAnalytics.cs
  Packages/manifest.json
  Packages/packages-lock.json
Labels: bug, programming

#155 Feature/implement initial audio
  Assets/Audio/Ambient/Pub loop.ogg
  Assets/Audio/Ambient/Pub loop.ogg.meta
  Assets/Audio/Music/menu jazz drum loop.ogg
  Assets/Audio/Music/menu jazz drum loop.ogg.meta
  Assets/Audio/SFX/Instrument_Selections.meta
  Assets/Audio/SFX/Instrument_Selections/Double bass E.ogg
  Assets/Audio/SFX/Instrument_Selections/Double bass E.ogg.meta
  Assets/Audio/SFX/Instrument_Selections/Drums.ogg
  Assets/Audio/SFX/Instrument_Selections/Drums.ogg.meta
  Assets/Audio/SFX/Instrument_Selections/Electric bass E.ogg
  Assets/Audio/SFX/Instrument_Selections/Electric bass E.ogg.meta
  Assets/Audio/SFX/Instrument_Selections/Electric guitar E.ogg
  Assets/Audio/SFX/Instrument_Selections/Electric guitar E.ogg.meta
  Assets/Audio/SFX/Instrument_Selections/Saxophone G#.ogg
  Assets/Audio/SFX/Instrument_Selections/Saxophone G#.ogg.meta
  Assets/Audio/SFX/Instrument_Selections/Upright piano B.ogg
  Assets/Audio/SFX/Instrument_Selections/Upright piano B.ogg.meta
  Assets/Audio/SFX/Instrument_Selections/Vibraphone G#.ogg
  Assets/Audio/SFX/Instrument_Selections/Vibraphone G#.ogg.meta
  Assets/Audio/UI/Button_Sounds.meta
  Assets/Audio/UI/Button_Sounds/cancel.ogg
  Assets/Audio/UI/Button_Sounds/cancel.ogg.meta
  Assets/Audio/UI/Button_Sounds/confirm.ogg
  Assets/Audio/UI/Button_Sounds/confirm.ogg.meta
  Assets/Audio/UI/Button_Sounds/hover.mp3
  Assets/Audio/UI/Button_Sounds/hover.mp3.meta
  Assets/Audio/UI/Button_Sounds/selection.ogg
  Assets/Audio/UI/Button_Sounds/selection.ogg.meta
  Assets/Fonts/Grandstander/static/Grandstander-Black SDF.asset
  Assets/Fonts/Grandstander/static/Grandstander-Medium SDF.asset
  Assets/Fonts/Lato/Lato-Thin SDF.asset
  Assets/Particles.meta
  Assets/Particles/Particle System.prefab
  Assets/Particles/Particle System.prefab.meta
  Assets/Prefabs/Audio/AudioManager.prefab
  Assets/Prefabs/Stage/StagePosition.prefab
  Assets/Prefabs/UI/Act Canvas.prefab
  Assets/Prefabs/UI/ChapterCanvas.prefab
  Assets/Prefabs/UI/ChapterInfo.prefab
  Assets/Prefabs/UI/Settings/SettingsPopup.prefab
  Assets/Prefabs/UI/Settings/VolumeSettings.prefab
  Assets/Prefabs/UI/StageSelection/MusicianInfo.prefab
  Assets/Prefabs/UI/StageSelection/StageSelection.prefab
  Assets/Prefabs/UI/TrackInfoPopup.prefab
  Assets/Scenes/Act 1 Chapter 1.unity
  Assets/Scenes/Act 1 Chapter 2.unity
  Assets/Scenes/Act 1 Chapter 3.unity
  Assets/Scenes/Act 1.unity
  Assets/Scenes/Act 2.unity
  Assets/Scenes/MainMenu.unity
  Assets/Scripts/Audio/AudioWrapper.cs
  Assets/Scripts/Audio/CustomAudioSource.cs
  Assets/Scripts/Audio/MainMenuAudio.cs
  Assets/Scripts/Audio/MainMenuAudio.cs.meta
  Assets/Scripts/GameStructure/Act.cs
  Assets/Scripts/GameStructure/ActCanvas.cs
  Assets/Scripts/GameStructure/Chapter.cs
  Assets/Scripts/Managers/AudioManager.cs
  Assets/Scripts/UI/CoreGameplay/Stage/StagePosition.cs
  ProjectSettings/ProjectSettings.asset
Labels: asset implementation

#154 Add all current Unity Analytics events
  Assets/Scripts/Analytics/AnalyticsHandlerBase.cs
  Assets/Scripts/Analytics/UnityAnalyticsHandler.cs
  Assets/Scripts/Audio/AudioBuilderSystem.cs
  Assets/Scripts/Audio/PerformanceAudioController.cs
  Assets/Scripts/GameStructure/Act.cs
  Assets/Scripts/GameStructure/Chapter.cs
  Assets/Scripts/Managers/PerformanceController.cs
  Assets/Scripts/UI/CoreGameplay/Stage/StagePosition.cs
  Assets/Scripts/UI/CoreGameplay/Stage/StageSelection.cs
  Assets/Scripts/UI/Settings/ToggleAnalytics.cs
  Assets/Scripts/Utils/SaveSystem.cs
  Assets/Scripts/Utils/StSDebug.cs
Labels: programming

#157 Feature/some more UI
  Assets/Art/UI/home-button.png
  Assets/Art/UI/home-button.png.meta
  Assets/Art/UI/long-button.png
  Assets/Art/UI/long-button.png.meta
  Assets/Art/UI/round-button.png
  Assets/Art/UI/round-button.png.meta
  Assets/Fonts/Grandstander/static/Grandstander-Black SDF.asset
  Assets/Prefabs/Narrative/TestIntroNarrative/INTROACT.asset
  Assets/Prefabs/UI/Act Canvas.prefab
  Assets/Prefabs/UI/CreditsPopup.prefab
  Assets/Prefabs/UI/Settings/SettingsPopup.prefab
  Assets/Scenes/Act 2.unity
  Assets/Scenes/MainMenu.unity
  Packages/manifest.json
  Packages/packages-lock.json
Labels: asset implementation

#163 Add an exit game button to the main menu
  Assets/Scenes/MainMenu.unity
  Assets/Scripts/Utils/ExitGameHelper.cs
  Assets/Scripts/Utils/ExitGameHelper.cs.meta
  Assets/Scripts/Utils/UnityHelper.cs
Labels: graphics, programming
